// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ItemResult interface {
	IsItemResult()
}

type Item struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Item) IsItemResult() {}

type ItemNotFound struct {
	ID string `json:"id"`
}

func (ItemNotFound) IsItemResult() {}

type Query struct {
}
