package schema

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72-dev

import (
	"context"
	"fmt"

	"github.com/Yamashou/gqlgenc/v3/testdata/integration/fragment/domain"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*domain.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// OptionalUser is the resolver for the optionalUser field.
func (r *queryResolver) OptionalUser(ctx context.Context) (*domain.User, error) {
	panic(fmt.Errorf("not implemented: OptionalUser - optionalUser"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
