// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

type Profile struct {
	ID  string `json:"id"`
	Age int    `json:"age"`
}

type Query struct {
}

type User struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Profile Profile `json:"profile"`
}
