// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

// Fragment
type UserFragment1 struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *UserFragment1) GetName() string {
	if t == nil {
		t = &UserFragment1{}
	}
	return t.Name
}

type UserFragment2 struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *UserFragment2) GetName() string {
	if t == nil {
		t = &UserFragment2{}
	}
	return t.Name
}

// Structs

// OperationResponse
type UserOperation struct {
	User UserOperation_User "json:\"user\" graphql:\"user\""
}

func (t *UserOperation) GetUser() *UserOperation_User {
	if t == nil {
		t = &UserOperation{}
	}
	return &t.User
}

// Operation
const UserOperationDocument = `query UserOperation {
	user {
		name
		... UserFragment1
		... UserFragment2
	}
}
fragment UserFragment1 on User {
	name
	name
}
fragment UserFragment2 on User {
	name
}
`

var DocumentOperationNames = map[string]string{
	UserOperationDocument: "UserOperation",
}
