package clientgen

import (
	_ "embed" // used to load template file
	"fmt"

	"github.com/99designs/gqlgen/codegen/templates"

	"github.com/Yamashou/gqlgenc/v3/codegen"
	"github.com/Yamashou/gqlgenc/v3/config"
)

//go:embed template.tmpl
var template string

func RenderTemplate(cfg *config.Config, operations []*codegen.Operation) error {
	if err := templates.Render(templates.Options{
		PackageName:     cfg.GQLGencConfig.ClientGen.Package,
		Template:        template,
		TemplateFS:      nil,
		Filename:        cfg.GQLGencConfig.ClientGen.Filename,
		RegionTags:      false,
		GeneratedHeader: false,
		PackageDoc:      "// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.\n",
		FileNotice:      "",
		Data: map[string]any{
			"QueryPackage": cfg.GQLGencConfig.QueryGen.Pkg().Name(),
			"Operations":   operations,
		},
		Funcs:    nil,
		Packages: cfg.GQLGenConfig.Packages,
	}); err != nil {
		return fmt.Errorf("%s generating failed: %w", cfg.GQLGencConfig.ClientGen.Filename, err)
	}

	return nil
}
