package querygen

import (
	_ "embed" // used to load template file
	"fmt"

	"github.com/99designs/gqlgen/codegen/templates"
	"github.com/Yamashou/gqlgenc/v3/config"
	"github.com/Yamashou/gqlgenc/v3/generator"
)

//go:embed template.gotpl
var template string

func RenderTemplate(cfg *config.Config, fragments []*generator.Fragment, operations []*generator.Operation, operationResponses []*generator.OperationResponse, structSources []*generator.StructSource) error {
	if err := templates.Render(templates.Options{
		PackageName: cfg.GQLGencConfig.QueryGen.Package,
		Filename:    cfg.GQLGencConfig.QueryGen.Filename,
		Template:    template,
		Data: map[string]any{
			"Fragment":          fragments,
			"Operation":         operations,
			"OperationResponse": operationResponses,
			"StructSources":     structSources,
		},
		Packages:   cfg.GQLGenConfig.Packages,
		PackageDoc: "// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.\n",
		Funcs: map[string]any{
			"genGetters": generator.NewGenGettersGenerator(cfg.GQLGencConfig.QueryGen.Package).GenFunc(),
		},
	}); err != nil {
		return fmt.Errorf("%s generating failed: %w", cfg.GQLGencConfig.QueryGen.Filename, err)
	}

	return nil
}
