version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - canonicalheader # ヘッダーのキーをキャメルケースにするLint 不要なので停止
    - cyclop # Cyclomatic complexityがgqlgen側で生成されたコードから呼ばれるとかなり値大きくなってしまってそれを解消するのが難しそうなので、一旦無視
    - dupl
    - dupword # 冗長な単語を検出するLint 不要なので停止
    - errname # エラー変数の名前を制限する必要はないので無視
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - gosmopolitan # string literalに日本語を利用したいので停止
    - interfacebloat # interfaceの上限を指定するLint 不要なので停止
    - ireturn # interfaceを返すとerrになるが問題ないので無視
    - lll
    - maintidx # Cyclomaticなどは不要なので停止
    - mnd # マジックナンバーを厳密に禁止していないので停止
    - musttag # json tagを必須にするLint 不要なので停止
    - nestif
    - nilnil # return nil, nilをすることは、Optionalの値を返す場合などよくあることなので無視
    - nlreturn
    - paralleltest
    - protogetter # proto使ってないので停止
    - tagliatelle # jsonタグのフォーマットが外部APIやgenファイルの中で一つに統一されていないのでそれらをすべて除外しなければいけない。除外するファイルが多いので一旦無視
    - testpackage
    - varnamelen # 変数名の長さを制限するのは不要なので停止
    - wrapcheck # xerrors.Errorfを使っているとエラーがラップされていない判定になっているみたいなので、一旦無視
    - wsl
  settings:
    depguard: # filesの判定は絶対パスに対して行われるので必ず先頭には**をつける必要がある。
      rules:
        gqlparserv1:
          deny:
            - pkg: ^github.com/vektah/gqlparser$
              desc: use github.com/vektah/gqlparser/v2
        gqlgencv1:
          deny:
            - pkg: github.com/builtbystack/erp/server/src/lib/ctxvalue
              desc: usecaseパッケージでctxvalueパッケージの使用は禁止されています
    errcheck:
      exclude-functions:
        - Write
        - Copy
        - WriteString
        - Render
    exhaustruct:
      include:
        - .+Input
        - .+Payload
        - .+/offset\.Statement
        - .+/seek\.Statement
      exclude:
        - github.com/builtbystack/erp/server/src/domain/shopifyadmin\..+Input$
    forbidigo: # forbidに一致する識別子をエラーにする
      forbid:
        - pattern: ^print.*$
        - pattern: ^log\.Debugf.*$
        - pattern: ^fmt\.Print.*$
        - pattern: ^fmt\.Errorf.*$
        - pattern: ^errors\.New.*$ # xerrors.Newを使う
        - pattern: ^xerrors\.New.*$ # src/lib/domerr/error\.go 以外ではxerrors.Errorfを使う
        - pattern: ^sort\..*$ # slices packageを使う
        - pattern: ^time\.Parse$ # time.ParseInLocationを使う
        - pattern: '[mM]etafiled'
        - pattern: '[gG]rahp[qQ][lL]'
        - pattern: '[cC]lerkUserID'
      analyze-types: true
    gomoddirectives:
      replace-local: true
    gosec:
      excludes:
        - G101 # G101: Potential hardcoded credentials の誤検出が多いので無視
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell: # コメントとテキストのスペルミスをチェックする
      extra-words: # 最初の1文字目は大文字・小文字に関係なく対象となる。途中に大文字が入ると検出されない。
        - typo: metafiled
          correction: metafield
        - typo: grahpql
          correction: graphql
        - typo: clerkuserid
          correction: userClerkID
        - typo: serverity
          correction: severity
    nakedret:
      max-func-lines: 1
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    perfsprint:
      strconcat: false # fmt.Sprintf("%s a", text) を text + "a" にするよう言われるがいったん無視
    staticcheck:
      checks:
        - all
        - -SA1019
        - -QF1008 # could remove embedded field "Decimal" from selector (staticcheck)
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Test
      - linters:
          - asciicheck # ユニットテストで日本語名つけられないのでoff
        path: _test\.go
      # xerrors
      - linters:
          - err113 # エラーラップのエラーだが、エラーラップを実装する処理なので無視する
          - forbidigo # errors.Newやfmt.Errorfを使ってエラーラップを実装しているので無視する
        path: src/lib/xerrors/.*\.go
      - linters:
          - forbidigo # xerrors.Newを利用してエラーを定義する場所なので許可する。
        path: src/lib/domerr/error\.go
        text: use of `xerrors.New` forbidden by pattern
      # resolverの未使用のctx変数
      - linters:
          - revive
        path: src/handler/.*/.*\.resolvers\.go
        text: seems to be unused, consider removing or renaming it as _
      # cmd
      - linters:
          - err113 # cmdでは `fmt\.Print.*`　や printの利用を許可する
          - forbidigo # cmdでは `fmt\.Errorf.*`　や printの利用を許可する
        path: cmd/.*/.*/.*\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - .*_gen\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vektah/gqlparser)
        - prefix(github.com/99designs/gqlgen)
        - prefix(github.com/Yamashou/gqlgenc)
  exclusions:
    generated: lax
    paths:
      - .*_gen\.go$
      - third_party$
      - builtin$
      - examples$
