linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  unparam:
    check-exported: true
  nakedret:
    max-func-lines: 1


linters:
  enable-all: true
  disable:
    - testpackage
    - nestif
    - godot
    - wsl
    - lll
    - dupl
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - godox
    - gocognit
    - gocyclo
    - gomnd
    - err113
    - errorlint # TODO able this lint
    - forbidigo
    - cyclop
    - govet
    - errname
    - varnamelen
    - nilnil
    - exhaustruct
    - nonamedreturns
    - depguard
    - musttag
    - paralleltest
    - nlreturn
    - mnd
  fast: true

issues:
  fix: true
  exclude-files:
    - _test\.go
    - example/*/*.go
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - example
  exclude-rules:
    # Test
    - path: _test\.go
      text: "Using the variable on range scope `tt` in function literal"
      linters:
        - scopelint
    - path: _test\.go
      linters:
        - unused
        - structcheck
        - forcetypeassert
    - path: introspection/type.go
      linters:
        - structcheck # These types fits IntrospectionQuery
    - path: config/config.go
      text: "`Query` is unused" # used in main.go
      linters:
        - structcheck
    - path: graphqljson/graphql.go
      text: "`Extensions` is unused" # used in line 48
      linters:
        - structcheck
    - path: graphqljson/graphql.go
      text: "append to slice `frontier` with non-zero initialized length" # used in config/config.go
      linters:
        - makezero
    - path: client/client_test.go
      text: "should not use built-in type string as key for value; define your own type to avoid collisions"
      linters:
        - staticcheck
    - path: client/client_test.go
      linters:
        - revive
