version: "2"
linters:
  default: all
  disable:
    - asasalint
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - intrange
    - ireturn
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    govet:
      disable:
        - shadow
      enable-all: true
    nakedret:
      max-func-lines: 1
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - scopelint
        path: _test\.go
        text: Using the variable on range scope `tt` in function literal
      - linters:
          - forcetypeassert
          - structcheck
          - unused
        path: _test\.go
      - linters:
          - structcheck
        path: introspection/type.go
      - linters:
          - structcheck
        path: config/config.go
        text: '`Query` is unused'
      - linters:
          - structcheck
        path: graphqljson/graphql.go
        text: '`Extensions` is unused'
      - linters:
          - structcheck
        path: config/config.go
        text: '`ClientV2` is unused'
      - linters:
          - makezero
        path: graphqljson/graphql.go
        text: append to slice `frontier` with non-zero initialized length
      - linters:
          - staticcheck
        path: clientv2/client_test.go
        text: should not use built-in type string as key for value; define your own type to avoid collisions
      - linters:
          - revive
        path: clientv2/client_test.go
    paths:
      - _test\.go
      - example/*/*.go
      - example
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - _test\.go
      - example/*/*.go
      - example
      - third_party$
      - builtin$
      - examples$
