version: "2"
linters:
  default: all
  settings:
    govet:
      enable-all: true
    nakedret:
      max-func-lines: 1
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - legacy
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/vektah/gqlparser)
        - Prefix(github.com/99designs/gqlgen)
        - Prefix(github.com/Yamashou/gqlgenc)
  exclusions:
    generated: lax
    paths:
      - .*_gen\.go$
      - third_party$
      - builtin$
      - examples$
