model:
  filename: ./model/models_gen.go
autobind:
  - github.com/Yamashou/gqlgenc/v3/example/github/model
client:
  filename: ./gen/client.go
models:
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
endpoint:
  url: https://api.github.com/graphql
  headers:
    Authorization: "Bearer ${GITHUB_TOKEN}" # public access token
query:
  - "./query/*.graphql"
generate:
  client: true
  clientInterfaceName: "GithubGraphQLClient"
  onlyUsedModels: true
