// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package query

import (
	"context"
	"github.com/Yamashou/gqlgenc/v3/testdata/integration/fragment/domain"

	"github.com/Yamashou/gqlgenc/v3/client"
)

type Client struct {
	client *client.Client
}

func NewClient(c *client.Client) *Client {
	return &Client{client: c}
}

func (c *Client) UserQuery(ctx context.Context, options ...client.Option) (*domain.UserQuery, error) {
	vars := map[string]any{}

	var res domain.UserQuery
	if err := c.client.Post(ctx, "UserQuery", domain.UserQueryDocument, vars, &res, options...); err != nil {
		return nil, err
	}

	return &res, nil
}
