package querygen

import (
	_ "embed" // used to load template file
	"fmt"

	"github.com/99designs/gqlgen/codegen/templates"
	"github.com/Yamashou/gqlgenc/v3/config"
	"github.com/Yamashou/gqlgenc/v3/gotype"
)

//go:embed template.gotpl
var template string

func RenderTemplate(cfg *config.Config, fragments []*gotype.Fragment, operations []*gotype.Operation, operationResponses []*gotype.OperationResponse, queryTypes []*gotype.QueryType) error {
	if err := templates.Render(templates.Options{
		PackageName: cfg.GQLGencConfig.QueryGen.Package,
		Filename:    cfg.GQLGencConfig.QueryGen.Filename,
		Template:    template,
		Data: map[string]any{
			"Fragments":          fragments,
			"Operations":         operations,
			"OperationResponses": operationResponses,
			"QueryTypes":         queryTypes,
		},
		Packages:   cfg.GQLGenConfig.Packages,
		PackageDoc: "// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.\n",
		Funcs: map[string]any{
			"getterFunc": gotype.GetterFunc(cfg.GQLGencConfig.QueryGen.Pkg().Path()),
		},
	}); err != nil {
		return fmt.Errorf("%s generating failed: %w", cfg.GQLGencConfig.QueryGen.Filename, err)
	}

	return nil
}
