package config

type GenerateConfig struct {
	Prefix        *NamingConfig `yaml:"prefix,omitempty"`
	Suffix        *NamingConfig `yaml:"suffix,omitempty"`
	UnamedPattern string        `yaml:"unamedPattern,omitempty"`
	// Deprecated: not working because it is generated by gqlgen
	Query *bool `yaml:"query,omitempty"`
	// Deprecated: not working because it is generated by gqlgen
	Mutation                     *bool   `yaml:"mutation,omitempty"`
	Client                       *bool   `yaml:"client,omitempty"`
	ClientInterfaceName          *string `yaml:"clientInterfaceName,omitempty"`
	NullableInputOmittable       bool    `yaml:"nullableInputOmittable,omitempty"`
	EnableClientJsonOmitemptyTag *bool   `yaml:"enableClientJsonOmitemptyTag,omitempty"`
	EnableClientJsonOmitzeroTag  *bool   `yaml:"enableClientJsonOmitzeroTag,omitempty"`

	// Deprecated: not working because v1 is deleted. Must use ClientV2
	// if true, used client v2 in generate code
	ClientV2                     bool  `yaml:"clientV2,omitempty"`
	StructFieldsAlwaysPointers   *bool `yaml:"structFieldsAlwaysPointers,omitempty"`
	InlineFragmentAlwaysPointers *bool `yaml:"inlineFragmentAlwaysPointers,omitempty"`
	OnlyUsedModels               *bool `yaml:"onlyUsedModels,omitempty"`
}

func (c *GenerateConfig) ShouldGenerateClient() bool {
	if c == nil {
		return true
	}

	if c.Client != nil && !*c.Client {
		return false
	}

	return true
}

func (c *GenerateConfig) GetClientInterfaceName() *string {
	if c == nil {
		return nil
	}

	return c.ClientInterfaceName
}

// applyDefaults fills the unset boolean options with their defaults.
//
// Arguments:
//   - none
//
// Returns:
//   - none
//
// Preconditions:
//   - c is not nil
//
// Postconditions:
//   - StructFieldsAlwaysPointers defaults to true, InlineFragmentAlwaysPointers to false,
//     EnableClientJsonOmitemptyTag to true, and EnableClientJsonOmitzeroTag to false
//   - options that were already set are left unchanged
func (c *GenerateConfig) applyDefaults() {
	if c.StructFieldsAlwaysPointers == nil {
		c.StructFieldsAlwaysPointers = boolPointer(true)
	}

	if c.InlineFragmentAlwaysPointers == nil {
		c.InlineFragmentAlwaysPointers = boolPointer(false)
	}

	if c.EnableClientJsonOmitemptyTag == nil {
		c.EnableClientJsonOmitemptyTag = boolPointer(true)
	}

	if c.EnableClientJsonOmitzeroTag == nil {
		c.EnableClientJsonOmitzeroTag = boolPointer(false)
	}
}

// boolPointer returns a pointer to b.
//
// Arguments:
//   - b: the value
//
// Returns:
//   - *bool: a pointer to a copy of b
//
// Preconditions:
//   - none
//
// Postconditions:
//   - none
func boolPointer(b bool) *bool {
	return &b
}

type NamingConfig struct {
	Query    string `yaml:"query,omitempty"`
	Mutation string `yaml:"mutation,omitempty"`
}
