model:
  package: generated
  filename: ./model/models_gen.go 
client:
  package: generated
  filename: ./gen/client.go 
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  Date:
    model: github.com/99designs/gqlgen/graphql.Time
schema:
  - "./schema/**/*.graphql"
query:
  - "./query/*.graphql" 
generate:
  onlyUsedModels: true
