// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

// Fragment
type UserFragment1 struct {
	Name string "json:\"name\" graphql:\"name\""
}

type UserFragment2 struct {
	Name string "json:\"name\" graphql:\"name\""
	User struct {
		Name string "json:\"name\""
	}  `graphql:"... on User"`
}

// Structs

// OperationResponse
type UserOperation struct {
	User struct {
		Name string "json:\"name\" graphql:\"name\""
		UserFragment1
		UserFragment2
		User struct {
			Name string "json:\"name\""
			UserFragment1
			UserFragment2
		}  `graphql:"... on User"`
	} "json:\"user\" graphql:\"user\""
}

// Operation
const UserOperationDocument = `query UserOperation {
	user {
		name
		... UserFragment1
		... UserFragment2
		... on User {
			name
			... UserFragment1
			... UserFragment2
		}
	}
}
fragment UserFragment1 on User {
	name
	name
}
fragment UserFragment2 on User {
	name
	... on User {
		name
	}
}
`

var DocumentOperationNames = map[string]string{
	UserOperationDocument: "UserOperation",
}
