// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

// Fragment
type UserFragment1 struct {
	Name string "json:\"name\" graphql:\"name\""
	Profile userFragment1_Profile "json:\"profile\" graphql:\"profile\""
}

type UserFragment2 struct {
	Name string "json:\"name\" graphql:\"name\""
}

type userFragment1_Profile struct {
	Age int "json:\"age\""
}

// Structs

// OperationResponse
type UserOperation struct {
	User struct {
		Name string "json:\"name\" graphql:\"name\""
		UserFragment1
		UserFragment2
	} "json:\"user\" graphql:\"user\""
}

// Operation
const UserOperationDocument = `query UserOperation {
	user {
		name
		profile {
			age
		}
		... UserFragment1
		... UserFragment2
	}
}
fragment UserFragment1 on User {
	name
	name
	profile {
		age
	}
}
fragment UserFragment2 on User {
	name
}
	user {
		name
		... UserFragment1
		... UserFragment2
	}
}
`

var DocumentOperationNames = map[string]string{
	UserOperationDocument: "UserOperation",
}
