model:
  filename: ./gen/models_gen.go
client:
  filename: ./gen/client.go
endpoint:
  url: http://localhost:8080/query #https://github.com/savel999/graphql-file-info
query:
  - "./query/*.graphql"
generate:
  client: true
