schema:
  - ./schema/schema.graphql
model:
  filename: ./model/models_gen.go
client:
  filename: ./gen/client.go
models:
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
query:
  - "./query/*.graphql"
generate:
  clientV2: true
  clientInterfaceName: "GithubGraphQLClient"
